### ISSUE TITLE
Implement email content transformation according Content-Transfer-Encoding header

### ISSUE THREAD

**Issue by mixas27** [jtalks-org/pochta#12]
Non-ASCII characters are not supported by SMTP protocol and shuld be transformed into ASCII before sending email. Currently pochta shows this emails "as is".
As a user I want to be able to view emails with non-ASCII characters in readdable form.
Note: MimeMessage can contain several MimeParts and each MimePart can have own headers.

**Comment by ctapobep** [comment]
@jk1 would you have time to implement this in Pochta? Currently we need only base64 transformation.

Pochta may have a separate JSON field with "body as is" and "user friendly body" or it may use content type from HTTP Request it gets from REST client in order to determine in what form it should spit out the content.

**Comment by jk1** [comment]
@ctapobep, sure

**Comment by jk1** [comment]
So I've added some basic decoder to show a mail in a pseudo-rendered readable form. Mail JSON now contains both rendered and raw mail versions. Never tested it on really complex samples though)

@mixas27, @ctapobep please let me know if current implementation suits your needs
